services:
  proxy:
    image: nginx:latest
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
      - moodle_base:/var/www/html:ro

  moodle:
    build: .
    depends_on:
      db:
        condition: service_healthy
    image: idems/moodle:latest
    environment:
      MAXIMA_URL: http://maxima:8080/maxima
      MOODLE_ADMIN_USER: admin
      MOODLE_ADMIN_PASS: pa55word
      MOODLE_ADMIN_EMAIL: admin@example.com
      MOODLE_FULL_NAME: Example Moodle site
      MOODLE_SHORT_NAME: example
      MOODLE_SUPPORT_EMAIL: support@example.com
      MOODLE_DB_TYPE: pgsql
      MOODLE_DB_HOST: db
      MOODLE_DB_PORT_NUMBER: "5432"
      MOODLE_DB_USER: postgres
      MOODLE_DB_NAME: postgres
      MOODLE_DB_PASS: pgpassword
      MOODLE_REVERSE_PROXY: "true"
      MOODLE_SMTP_HOST: mail
      MOODLE_SMTP_PORT: "1025"
      MOODLE_SMTP_USER: moodle
      MOODLE_SMTP_PASSWORD: moodle
      MOODLE_WWW_ROOT: http://localhost:8000
    volumes:
      - moodle_base:/var/www/html
      - moodle_data:/var/www/moodledata
  cron:
    command: []
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/opt/idems/cron.sh"]
    image: idems/moodle:latest
    volumes:
      - moodle_base:/var/www/html
      - moodle_data:/var/www/moodledata
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pgpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
    volumes:
      - db:/var/lib/postgresql/data
  maxima:
    image: mathinstitut/goemaxima:2025073100-latest
    restart: always
  mail:
    image: axllent/mailpit:v1.27
    restart: unless-stopped
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 'yes'
      MP_SMTP_AUTH_ALLOW_INSECURE: 'yes'
    ports:
      - '8025:8025'
volumes:
  db:
    driver: local
  moodle_base:
    driver: local
  moodle_data:
    driver: local
